### PR TITLE
fix `no previous prototype` for `showmodule_read()`

### LINKED ISSUE #1: Can't compile in 6.9.6-arch1-1
I don't really think its a kernel version issue at all, make fails complaining about an implicit declaration:
```bash
make -C /lib/modules/6.9.6-arch1-1/build M=$PWD
make[1]: Entering directory '/usr/lib/modules/6.9.6-arch1-1/build'
  CC [M]  /home/skelly/nitara2/nitara2.o
/home/skelly/nitara2/nitara2.c:166:9: error: no previous prototype for ‘showmodule_read’ [-Werror=missing-prototypes]
  166 | ssize_t showmodule_read(struct file *unused_file, char *buffer, size_t len, loff_t *off)
      |         ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [scripts/Makefile.build:244: /home/skelly/nitara2/nitara2.o] Error 1
make[2]: *** [/usr/lib/modules/6.9.6-arch1-1/build/Makefile:1918: /home/skelly/nitara2] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.9.6-arch1-1/build'
make: *** [Makefile:2: all] Error 2
```
Tried modifying Kbuild:
```bash
MODNAME     ?= nitara2
$(MODNAME)-m       += $(MODNAME).o module_hunter.o 
ccflags-y   += -Werror 
KBUILD_CFLAGS   := $(filter-out -pg,$(KBUILD_CFLAGS))
KBUILD_CFLAGS   := $(filter-out -mfentry,$(KBUILD_CFLAGS))
```
And `make` only created modules.order and Module.symvers

### PR DESCRIPTION
**Pull request by ksen-lin**
declare `showmodule_read()` static so that it wont trigger `-Wmissing-declarations` for no unneeded prototype (fixes #1)

### CODE REVIEW

**Comment by lil-skelly** [comment]
Good! I should have made a PR, but I totally forgot about it, better late than never though hahah
