### ISSUE TITLE
Can't compile in 6.9.6-arch1-1

### ISSUE THREAD

**Issue by lil-skelly** [ksen-lin/nitara2#1]
I don't really think its a kernel version issue at all, make fails complaining about an implicit declaration:
```bash
make -C /lib/modules/6.9.6-arch1-1/build M=$PWD
make[1]: Entering directory '/usr/lib/modules/6.9.6-arch1-1/build'
  CC [M]  /home/skelly/nitara2/nitara2.o
/home/skelly/nitara2/nitara2.c:166:9: error: no previous prototype for ‘showmodule_read’ [-Werror=missing-prototypes]
  166 | ssize_t showmodule_read(struct file *unused_file, char *buffer, size_t len, loff_t *off)
      |         ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [scripts/Makefile.build:244: /home/skelly/nitara2/nitara2.o] Error 1
make[2]: *** [/usr/lib/modules/6.9.6-arch1-1/build/Makefile:1918: /home/skelly/nitara2] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.9.6-arch1-1/build'
make: *** [Makefile:2: all] Error 2
```
Tried modifying Kbuild:
```bash
MODNAME     ?= nitara2
$(MODNAME)-m       += $(MODNAME).o module_hunter.o 
ccflags-y   += -Werror 
KBUILD_CFLAGS   := $(filter-out -pg,$(KBUILD_CFLAGS))
KBUILD_CFLAGS   := $(filter-out -mfentry,$(KBUILD_CFLAGS))
```
And `make` only created modules.order and Module.symvers

**Comment by lil-skelly** [comment]
Does look like a kernel version issue after all (tested on ubuntu 20.04 VM)

**Comment by ksen-lin** [comment]
hi! i guess it's better late than never :D

thanks for reporting. i finally dug a bit into [gcc docs](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wmissing-prototypes), and seemingly `-Wmissing-prototypes` found its way into the kernel, or whatever, right after i finished my code. Or maybe it's a compiler issue...
Anyway, either adding a prototype or making a function non-global fixed the warning
